# Generated by Django 2.2.8 on 2019-12-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bday_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_sub',
            field=models.BooleanField(default=False, verbose_name='Подписан?'),
            preserve_default=False,
        ),
    ]
