# Generated by Django 2.2.8 on 2019-12-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bday_admin', '0002_profile_is_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_sub',
            field=models.BooleanField(default=False, verbose_name='Подписан?'),
        ),
    ]
